version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${SQL_ROOT_PWD}
      MYSQL_DATABASE: ${SQL_DB}
      MYSQL_USER: ${SQL_USER}
      MYSQL_PASSWORD: ${SQL_PWD}
    ports:
      - "${SQL_PORT}:3306"
    volumes:
      - ${SQL_DATA_PATH}:/var/lib/mysql

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "${NOSQL_PORT}:27017"
    volumes:
      - ${NOSQL_DATA_PATH}:/data/db